Vagrant.configure("2") do |config|


  # Base box
  config.vm.box = "raring-64"
  config.vm.box_url = 
      "http://cloud-images.ubuntu.com/vagrant/raring/current/
       raring-server-cloudimg-amd64-vagrant-disk1.box"


  config.vm.provider :virtualbox do |vb| 
    # Memory usage
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    # Check the number of cpu cores you have/want to use
    vb.customize ["modifyvm", :id, "--cpus", "4"] 
  end

 
  # To use gui elements
  config.ssh.forward_x11 = true


  # Vagrant Cachier
  # vagrant plugin install vagrant-cachier
  if defined? config.cache
    config.cache.auto_detect = true
  end


  # Setup scripts
  config.vm.provision "shell", :path => "../provisions/vagrant_dir.sh"
  config.vm.provision "shell", :path => "../provisions/basic_tools.sh"
  config.vm.provision "shell", :path => "../provisions/node_source.sh"

end
